jobs:
  bump:
    if: "github.event_name == 'release' && github.event.action == 'created'"
    name: Bump minor version
    needs:
      - macWindowsPublish
      - manylinuxPublish
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Setup python 3.10
        uses: "actions/setup-python@v2"
        with:
          python-version: '3.10'
      - name: Install Rust
        uses: "actions-rs/toolchain@v1"
        with:
          override: 'true'
          toolchain: stable
      - name: Install dependencies
        run: "python -m pip install --upgrade pip\ncargo install cargo-bump\npython -m pip install poetry\ntouch Cargo.toml.orig\npython -m poetry install"
      - name: Bump and push
        run: "cargo bump patch\npoetry version patch\ngit config user.name github-actions\ngit config user.email github-actions@github.com\ngit add Cargo.toml pyproject.toml\ngit commit -m \"Bump version (automatic commit)\"\ngit push"
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Setup python 3.10
        uses: "actions/setup-python@v2"
        with:
          python-version: '3.10'
      - name: Install dhall
        uses: "dhall-lang/setup-dhall@v4"
        with:
          version: '1.40.1'
      - name: Install dependencies
        run: "python -m pip install --upgrade pip\npython -m pip install black isort autoflake"
      - if: "github.event.name != 'pull_request'"
        name: Check github actions workflow
        run: "dhall-to-yaml < .github/workflows/ci.dhall > expected.yml\ndiff expected.yml .github/workflows/ci.yml"
      - name: Check lint
        run: "isort . --check --diff\nblack . --check"
  macWindowsPublish:
    name: Build/test/publish
    needs:
      - lint
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: "actions/checkout@v2"
      - name: Install Rust
        uses: "actions-rs/toolchain@v1"
        with:
          override: 'true'
          toolchain: stable
      - name: "Setup python ${{ matrix.python-version }}"
        uses: "actions/setup-python@v2"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install dependencies
        run: "python -m pip install --upgrade pip\npython -m pip install poetry\ntouch Cargo.toml.orig\npython -m poetry install"
      - name: Build and test python package
        run: "python -m poetry run maturin build --release --strip --interpreter python${{ matrix.python-version }}\npython -m poetry run maturin develop\npython -m poetry run pytest tests"
      - if: "matrix.os == 'windows-latest'"
        name: Install wheels
        run: "python -m pip install --find-links=target\\wheels dhall"
      - if: "matrix.os != 'windows-latest'"
        name: Install wheels
        run: "python -m pip install target/wheels/dhall*.whl"
      - env:
          MATURIN_PASSWORD: "${{ secrets.PYPI }}"
        if: "startsWith(github.ref, 'refs/tags/') && github.event_name == 'release' && github.event.action == 'created'"
        name: PyPI publish
        run: "python -m poetry run maturin publish --username __token__ --interpreter python${{ matrix.python-version }}"
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: "startsWith(github.ref, 'refs/tags/') && github.event_name == 'release' && github.event.action == 'created'"
        name: Release
        uses: "softprops/action-gh-release@v1"
        with:
          files: "target/wheels/dhall*.whl"
    strategy:
      fail-fast: true
      matrix:
        os:
          - macos-latest
          - windows-latest
        python-version:
          - '3.6'
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
  manylinuxPublish:
    container: quay.io/pypa/manylinux_2_24_x86_64
    name: Build/test/publish
    needs:
      - lint
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
      - name: Install Rust
        uses: "actions-rs/toolchain@v1"
        with:
          override: 'true'
          toolchain: stable
      - name: Install dependencies
        run: "python3.6 -m pip install --upgrade pip\npython3.6 -m pip install poetry\ntouch Cargo.toml.orig\npython3.6 -m poetry install"
      - name: Build and test python package
        run: "python3.6 -m poetry run maturin build --release --strip --interpreter python3.6\npython3.6 -m poetry run maturin develop\npython3.6 -m poetry run pytest tests"
      - if: "matrix.os == 'windows-latest'"
        name: Install wheels
        run: "python3.6 -m pip install --find-links=target\\wheels dhall"
      - if: "matrix.os != 'windows-latest'"
        name: Install wheels
        run: "python3.6 -m pip install target/wheels/dhall*.whl"
      - env:
          MATURIN_PASSWORD: "${{ secrets.PYPI }}"
        if: "startsWith(github.ref, 'refs/tags/') && github.event_name == 'release' && github.event.action == 'created'"
        name: PyPI publish
        run: python3.6 -m poetry run maturin publish --username __token__ --interpreter python3.6
      - name: Install dependencies
        run: "python3.7 -m pip install --upgrade pip\npython3.7 -m pip install poetry\ntouch Cargo.toml.orig\npython3.7 -m poetry install"
      - name: Build and test python package
        run: "python3.7 -m poetry run maturin build --release --strip --interpreter python3.7\npython3.7 -m poetry run maturin develop\npython3.7 -m poetry run pytest tests"
      - if: "matrix.os == 'windows-latest'"
        name: Install wheels
        run: "python3.7 -m pip install --find-links=target\\wheels dhall"
      - if: "matrix.os != 'windows-latest'"
        name: Install wheels
        run: "python3.7 -m pip install target/wheels/dhall*.whl"
      - env:
          MATURIN_PASSWORD: "${{ secrets.PYPI }}"
        if: "startsWith(github.ref, 'refs/tags/') && github.event_name == 'release' && github.event.action == 'created'"
        name: PyPI publish
        run: python3.7 -m poetry run maturin publish --username __token__ --interpreter python3.7
      - name: Install dependencies
        run: "python3.8 -m pip install --upgrade pip\npython3.8 -m pip install poetry\ntouch Cargo.toml.orig\npython3.8 -m poetry install"
      - name: Build and test python package
        run: "python3.8 -m poetry run maturin build --release --strip --interpreter python3.8\npython3.8 -m poetry run maturin develop\npython3.8 -m poetry run pytest tests"
      - if: "matrix.os == 'windows-latest'"
        name: Install wheels
        run: "python3.8 -m pip install --find-links=target\\wheels dhall"
      - if: "matrix.os != 'windows-latest'"
        name: Install wheels
        run: "python3.8 -m pip install target/wheels/dhall*.whl"
      - env:
          MATURIN_PASSWORD: "${{ secrets.PYPI }}"
        if: "startsWith(github.ref, 'refs/tags/') && github.event_name == 'release' && github.event.action == 'created'"
        name: PyPI publish
        run: python3.8 -m poetry run maturin publish --username __token__ --interpreter python3.8
      - name: Install dependencies
        run: "python3.9 -m pip install --upgrade pip\npython3.9 -m pip install poetry\ntouch Cargo.toml.orig\npython3.9 -m poetry install"
      - name: Build and test python package
        run: "python3.9 -m poetry run maturin build --release --strip --interpreter python3.9\npython3.9 -m poetry run maturin develop\npython3.9 -m poetry run pytest tests"
      - if: "matrix.os == 'windows-latest'"
        name: Install wheels
        run: "python3.9 -m pip install --find-links=target\\wheels dhall"
      - if: "matrix.os != 'windows-latest'"
        name: Install wheels
        run: "python3.9 -m pip install target/wheels/dhall*.whl"
      - env:
          MATURIN_PASSWORD: "${{ secrets.PYPI }}"
        if: "startsWith(github.ref, 'refs/tags/') && github.event_name == 'release' && github.event.action == 'created'"
        name: PyPI publish
        run: python3.9 -m poetry run maturin publish --username __token__ --interpreter python3.9
      - name: Install dependencies
        run: "python3.10 -m pip install --upgrade pip\npython3.10 -m pip install poetry\ntouch Cargo.toml.orig\npython3.10 -m poetry install"
      - name: Build and test python package
        run: "python3.10 -m poetry run maturin build --release --strip --interpreter python3.10\npython3.10 -m poetry run maturin develop\npython3.10 -m poetry run pytest tests"
      - if: "matrix.os == 'windows-latest'"
        name: Install wheels
        run: "python3.10 -m pip install --find-links=target\\wheels dhall"
      - if: "matrix.os != 'windows-latest'"
        name: Install wheels
        run: "python3.10 -m pip install target/wheels/dhall*.whl"
      - env:
          MATURIN_PASSWORD: "${{ secrets.PYPI }}"
        if: "startsWith(github.ref, 'refs/tags/') && github.event_name == 'release' && github.event.action == 'created'"
        name: PyPI publish
        run: python3.10 -m poetry run maturin publish --username __token__ --interpreter python3.10
      - env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        if: "startsWith(github.ref, 'refs/tags/') && github.event_name == 'release' && github.event.action == 'created'"
        name: Release
        uses: "softprops/action-gh-release@v1"
        with:
          files: "target/wheels/dhall*.whl"
name: CI
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  release:
    types:
      - created
  schedule:
    - cron: "20 23 * * 6"
